name: Build and Test

on: [ push ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'

      - name: Install uv and pipx
        run: |
          pip install uv && pip install pipx

      - name: Install global dependencies
        run: |
          pipx install uv && pipx install "coderoller" && \
          pipx install isort && pipx install black && pipx install bandit && \
          pipx install pylint && pipx install pre-commit && pipx install poetry && pipx install hatch

      - name: Install Dependencies
        run: uv sync

      - name: Run make check
        run: chmod +x *.sh && uv run make check

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
