name: Build and Test

on: [ push ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.14'

      - name: Install uv and pipx
        run: |
          pip install uv && pip install pipx

      - name: Install global dependencies
        run: |
          pipx install uv && pipx install "coderoller" && \
          pipx install isort && pipx install black && pipx install bandit && \
          pipx install pylint && pipx install pre-commit && pipx install poetry && pipx install hatch

      - name: Install Dependencies
        run: uv sync

      - name: Run make check
        run: chmod +x *.sh && uv run make check

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
